config/routes.rb
Ddjj3::Application.routes.draw do
  
  get "adm_ddjj/verDDJJAgente"

  get "adm_ddjj/ListarDDJJsIncompatibles"

  get "adm_ddjj/ListarDDJJsEscuela"

  get "adm_ddjj/ListarDDJJsAgente"

  get "adm_ddjj/AprobarItemDDJJ"

  get "adm_ddjj/ObservarItemDDJJ"

  get "adm_ddjj/RechazarItemDDJJ"

  get "adm_ddjj/AgregarItemDDJJ"

  get "adm_ddjj/EditarItemDDJJ"

  get "adm_ddjj/EliminarItemDDJJ"

  get "adm_ddjj/EditarGrupoHorarioItemDDJJ"

  get "adm_ddjj/AgregarGrupoHorarioItemDDJJ"

  get "adm_ddjj/EliminarGrupoHorarioItemDDJJ"

  get "adm_ddjj/verDDJJ"

  get "adm_ddjj/verDDJJsAgente"

  get "adm_ddjj/ModificarDDJJ"

  get "adm_ddjj/CargarDDJJ"

  get "adm_ddjj/ListarDDJJs"

  get "adm_ddjj/ListarDDJJsI"

  get "adm_ddjj/verDdjj"

  get "adm_ddjj/ModificarDdjj"

  get "adm_ddjj/CargarDdjj"

  get "adm_ddjj/ListarDdjjs"

  get "adm_ddjj/EliminarDdjj"

  resources :grupo_horario_item_ddjjs

  resources :item_ddjjs

  resources :materia_cargos

  resources :funcions

  resources :ddjjs

  resources :localidads

  resources :provincias

  resources :organizacions

  resources :domicilios

  resources :users

  get "session/login"

  get "session/logout"

  post "relacion_agente_profesion/guardar"
  
 
        
  get "relacion_agente_profesion/agregarProfesionAgente"

  resources :profesion_agentes

  resources :profesions

  resources :agentes

end

app/models/agente.rb
class Agente < ActiveRecord::Base
  #-------------controles relacionales--------
  has_many :profesion_agente
  #-------------validaciones------------------
  validates :dni, :presence => true, :uniqueness => true,  :numericality => true
  
  validates :nombre, :presence => true
  validates :apellido, :presence => true
end

app/models/ddjj.rb
class Ddjj < ActiveRecord::Base
end

app/models/domicilio.rb
class Domicilio < ActiveRecord::Base
end

app/models/funcion.rb
class Funcion < ActiveRecord::Base
end

app/models/item_ddjj.rb
class ItemDdjj < ActiveRecord::Base
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
end

app/models/materia_cargo.rb
class MateriaCargo < ActiveRecord::Base
end

app/models/organizacion.rb
class Organizacion < ActiveRecord::Base
end

app/models/profesion.rb
class Profesion < ActiveRecord::Base
   has_many :profesion_agente
end

app/models/profesion_agente.rb
class ProfesionAgente < ActiveRecord::Base
  #supuestamente comprueba que sea unico el par
  validates :agente_id, :uniqueness => {:scope => :profesion_id}
  #validaciones de existencias
  validates :agente_id, :presence => true
  validates :profesion_id, :presence => true 
  #para establecer la relacion, desde la consola 'rails console' funca
  belongs_to :agente
  belongs_to :profesion
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/item_ddjjs_controller.rb
class ItemDdjjsController < ApplicationController
  # GET /item_ddjjs
  # GET /item_ddjjs.xml
  def index
    @item_ddjjs = ItemDdjj.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @item_ddjjs }
    end
  end

  # GET /item_ddjjs/1
  # GET /item_ddjjs/1.xml
  def show
    @item_ddjj = ItemDdjj.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item_ddjj }
    end
  end

  # GET /item_ddjjs/new
  # GET /item_ddjjs/new.xml
  def new
    @item_ddjj = ItemDdjj.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item_ddjj }
    end
  end

  # GET /item_ddjjs/1/edit
  def edit
    @item_ddjj = ItemDdjj.find(params[:id])
  end

  # POST /item_ddjjs
  # POST /item_ddjjs.xml
  def create
    @item_ddjj = ItemDdjj.new(params[:item_ddjj])

    respond_to do |format|
      if @item_ddjj.save
        format.html { redirect_to(@item_ddjj, :notice => 'Item ddjj was successfully created.') }
        format.xml  { render :xml => @item_ddjj, :status => :created, :location => @item_ddjj }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item_ddjj.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /item_ddjjs/1
  # PUT /item_ddjjs/1.xml
  def update
    @item_ddjj = ItemDdjj.find(params[:id])

    respond_to do |format|
      if @item_ddjj.update_attributes(params[:item_ddjj])
        format.html { redirect_to(@item_ddjj, :notice => 'Item ddjj was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item_ddjj.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /item_ddjjs/1
  # DELETE /item_ddjjs/1.xml
  def destroy
    @item_ddjj = ItemDdjj.find(params[:id])
    @item_ddjj.destroy

    respond_to do |format|
      format.html { redirect_to(item_ddjjs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/adm_ddjj_helper.rb
module AdmDdjjHelper
end

app/helpers/agentes_helper.rb
module AgentesHelper
end

app/helpers/ddj_js_helper.rb
module DdjJsHelper
end

app/helpers/domicilios_helper.rb
module DomiciliosHelper
end

app/helpers/funcions_helper.rb
module FuncionsHelper
end

app/helpers/item_ddj_js_helper.rb
module ItemDdjJsHelper
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/profesions_helper.rb
module ProfesionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/item_ddjjs/_form.html.erb
<%= form_for(@item_ddjj) do |f| %>
  <% if @item_ddjj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_ddjj.errors.count, "error") %> prohibited this item_ddjj from being saved:</h2>

      <ul>
      <% @item_ddjj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DDJJ_id %><br />
    <%= f.text_field :DDJJ_id %>
  </div>
  <div class="field">
    <%= f.label :numeroDeItem %><br />
    <%= f.text_field :numeroDeItem %>
  </div>
  <div class="field">
    <%= f.label :organizacion_id %><br />
    <%= f.text_field :organizacion_id %>
  </div>
  <div class="field">
    <%= f.label :materiaCargo_id %><br />
    <%= f.text_field :materiaCargo_id %>
  </div>
  <div class="field">
    <%= f.label :funcion_id %><br />
    <%= f.text_field :funcion_id %>
  </div>
  <div class="field">
    <%= f.label :FechaDeAlta %><br />
    <%= f.date_select :FechaDeAlta %>
  </div>
  <div class="field">
    <%= f.label :CantidadDeHorasSemanales %><br />
    <%= f.text_field :CantidadDeHorasSemanales %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_ddjjs/edit.html.erb
<h1>Editing item_ddjj</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_ddjj %> |
<%= link_to 'Back', item_ddjjs_path %>

app/views/item_ddjjs/index.html.erb
<h1>Listing item_ddjjs</h1>

<table>
  <tr>
    <th>Ddjj</th>
    <th>Numerodeitem</th>
    <th>Organizacion</th>
    <th>Materiacargo</th>
    <th>Funcion</th>
    <th>Fechadealta</th>
    <th>Cantidaddehorassemanales</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_ddjjs.each do |item_ddjj| %>
  <tr>
    <td><%= item_ddjj.DDJJ_id %></td>
    <td><%= item_ddjj.numeroDeItem %></td>
    <td><%= item_ddjj.organizacion_id %></td>
    <td><%= item_ddjj.materiaCargo_id %></td>
    <td><%= item_ddjj.funcion_id %></td>
    <td><%= item_ddjj.FechaDeAlta %></td>
    <td><%= item_ddjj.CantidadDeHorasSemanales %></td>
    <td><%= link_to 'Show', item_ddjj %></td>
    <td><%= link_to 'Edit', edit_item_ddjj_path(item_ddjj) %></td>
    <td><%= link_to 'Destroy', item_ddjj, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item ddjj', new_item_ddjj_path %>

app/views/item_ddjjs/new.html.erb
<h1>New item_ddjj</h1>

<%= render 'form' %>

<%= link_to 'Back', item_ddjjs_path %>

app/views/item_ddjjs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ddjj:</b>
  <%= @item_ddjj.DDJJ_id %>
</p>

<p>
  <b>Numerodeitem:</b>
  <%= @item_ddjj.numeroDeItem %>
</p>

<p>
  <b>Organizacion:</b>
  <%= @item_ddjj.organizacion_id %>
</p>

<p>
  <b>Materiacargo:</b>
  <%= @item_ddjj.materiaCargo_id %>
</p>

<p>
  <b>Funcion:</b>
  <%= @item_ddjj.funcion_id %>
</p>

<p>
  <b>Fechadealta:</b>
  <%= @item_ddjj.FechaDeAlta %>
</p>

<p>
  <b>Cantidaddehorassemanales:</b>
  <%= @item_ddjj.CantidadDeHorasSemanales %>
</p>


<%= link_to 'Edit', edit_item_ddjj_path(@item_ddjj) %> |
<%= link_to 'Back', item_ddjjs_path %>