config/routes.rb
Ddjj3::Application.routes.draw do
  
  get "adm_ddjj/verDDJJAgente"

  get "adm_ddjj/ListarDDJJsIncompatibles"

  get "adm_ddjj/ListarDDJJsEscuela"

  get "adm_ddjj/ListarDDJJsAgente"

  get "adm_ddjj/AprobarItemDDJJ"

  get "adm_ddjj/ObservarItemDDJJ"

  get "adm_ddjj/RechazarItemDDJJ"

  get "adm_ddjj/AgregarItemDDJJ"

  get "adm_ddjj/EditarItemDDJJ"

  get "adm_ddjj/EliminarItemDDJJ"

  get "adm_ddjj/EditarGrupoHorarioItemDDJJ"

  get "adm_ddjj/AgregarGrupoHorarioItemDDJJ"

  get "adm_ddjj/EliminarGrupoHorarioItemDDJJ"

  get "adm_ddjj/verDDJJ"

  get "adm_ddjj/verDDJJsAgente"

  get "adm_ddjj/ModificarDDJJ"

  get "adm_ddjj/CargarDDJJ"

  get "adm_ddjj/ListarDDJJs"

  get "adm_ddjj/ListarDDJJsI"

  get "adm_ddjj/verDdjj"

  get "adm_ddjj/ModificarDdjj"

  get "adm_ddjj/CargarDdjj"

  get "adm_ddjj/ListarDdjjs"

  get "adm_ddjj/EliminarDdjj"

  resources :grupo_horario_item_ddjjs

  resources :item_ddjjs

  resources :materia_cargos

  resources :funcions

  resources :ddjjs

  resources :localidads

  resources :provincias

  resources :organizacions

  resources :domicilios

  resources :users

  get "session/login"

  get "session/logout"

  post "relacion_agente_profesion/guardar"
  
 
        
  get "relacion_agente_profesion/agregarProfesionAgente"

  resources :profesion_agentes

  resources :profesions

  resources :agentes

end

app/models/agente.rb
class Agente < ActiveRecord::Base
  #-------------controles relacionales--------
  has_many :profesion_agente
  #-------------validaciones------------------
  validates :dni, :presence => true, :uniqueness => true,  :numericality => true
  
  validates :nombre, :presence => true
  validates :apellido, :presence => true
end

app/models/ddjj.rb
class Ddjj < ActiveRecord::Base
end

app/models/domicilio.rb
class Domicilio < ActiveRecord::Base
end

app/models/funcion.rb
class Funcion < ActiveRecord::Base
end

app/models/item_ddjj.rb
class ItemDdjj < ActiveRecord::Base
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
end

app/models/materia_cargo.rb
class MateriaCargo < ActiveRecord::Base
end

app/models/organizacion.rb
class Organizacion < ActiveRecord::Base
end

app/models/profesion.rb
class Profesion < ActiveRecord::Base
   has_many :profesion_agente
end

app/models/profesion_agente.rb
class ProfesionAgente < ActiveRecord::Base
  #supuestamente comprueba que sea unico el par
  validates :agente_id, :uniqueness => {:scope => :profesion_id}
  #validaciones de existencias
  validates :agente_id, :presence => true
  validates :profesion_id, :presence => true 
  #para establecer la relacion, desde la consola 'rails console' funca
  belongs_to :agente
  belongs_to :profesion
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/materia_cargos_controller.rb
class MateriaCargosController < ApplicationController
  # GET /materia_cargos
  # GET /materia_cargos.xml
  def index
    @materia_cargos = MateriaCargo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @materia_cargos }
    end
  end

  # GET /materia_cargos/1
  # GET /materia_cargos/1.xml
  def show
    @materia_cargo = MateriaCargo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @materia_cargo }
    end
  end

  # GET /materia_cargos/new
  # GET /materia_cargos/new.xml
  def new
    @materia_cargo = MateriaCargo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @materia_cargo }
    end
  end

  # GET /materia_cargos/1/edit
  def edit
    @materia_cargo = MateriaCargo.find(params[:id])
  end

  # POST /materia_cargos
  # POST /materia_cargos.xml
  def create
    @materia_cargo = MateriaCargo.new(params[:materia_cargo])

    respond_to do |format|
      if @materia_cargo.save
        format.html { redirect_to(@materia_cargo, :notice => 'Materia cargo was successfully created.') }
        format.xml  { render :xml => @materia_cargo, :status => :created, :location => @materia_cargo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @materia_cargo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /materia_cargos/1
  # PUT /materia_cargos/1.xml
  def update
    @materia_cargo = MateriaCargo.find(params[:id])

    respond_to do |format|
      if @materia_cargo.update_attributes(params[:materia_cargo])
        format.html { redirect_to(@materia_cargo, :notice => 'Materia cargo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @materia_cargo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /materia_cargos/1
  # DELETE /materia_cargos/1.xml
  def destroy
    @materia_cargo = MateriaCargo.find(params[:id])
    @materia_cargo.destroy

    respond_to do |format|
      format.html { redirect_to(materia_cargos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/adm_ddjj_helper.rb
module AdmDdjjHelper
end

app/helpers/agentes_helper.rb
module AgentesHelper
end

app/helpers/ddj_js_helper.rb
module DdjJsHelper
end

app/helpers/domicilios_helper.rb
module DomiciliosHelper
end

app/helpers/funcions_helper.rb
module FuncionsHelper
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/materia_cargos_helper.rb
module MateriaCargosHelper
end

app/helpers/profesions_helper.rb
module ProfesionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/materia_cargos/_form.html.erb
<%= form_for(@materia_cargo) do |f| %>
  <% if @materia_cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@materia_cargo.errors.count, "error") %> prohibited this materia_cargo from being saved:</h2>

      <ul>
      <% @materia_cargo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cant_horas_semanales %><br />
    <%= f.text_field :cant_horas_semanales %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materia_cargos/edit.html.erb
<h1>Editing materia_cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @materia_cargo %> |
<%= link_to 'Back', materia_cargos_path %>

app/views/materia_cargos/index.html.erb
<h1>Listing materia_cargos</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Cant horas semanales</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materia_cargos.each do |materia_cargo| %>
  <tr>
    <td><%= materia_cargo.codigo %></td>
    <td><%= materia_cargo.nombre %></td>
    <td><%= materia_cargo.cant_horas_semanales %></td>
    <td><%= link_to 'Show', materia_cargo %></td>
    <td><%= link_to 'Edit', edit_materia_cargo_path(materia_cargo) %></td>
    <td><%= link_to 'Destroy', materia_cargo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Materia cargo', new_materia_cargo_path %>

app/views/materia_cargos/new.html.erb
<h1>New materia_cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', materia_cargos_path %>

app/views/materia_cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @materia_cargo.codigo %>
</p>

<p>
  <b>Nombre:</b>
  <%= @materia_cargo.nombre %>
</p>

<p>
  <b>Cant horas semanales:</b>
  <%= @materia_cargo.cant_horas_semanales %>
</p>


<%= link_to 'Edit', edit_materia_cargo_path(@materia_cargo) %> |
<%= link_to 'Back', materia_cargos_path %>