config/routes.rb
Ddjj3::Application.routes.draw do
  
  get "adm_ddjj/verDDJJAgente"

  get "adm_ddjj/ListarDDJJsIncompatibles"

  get "adm_ddjj/ListarDDJJsEscuela"

  get "adm_ddjj/ListarDDJJsAgente"

  get "adm_ddjj/AprobarItemDDJJ"

  get "adm_ddjj/ObservarItemDDJJ"

  get "adm_ddjj/RechazarItemDDJJ"

  get "adm_ddjj/AgregarItemDDJJ"

  get "adm_ddjj/EditarItemDDJJ"

  get "adm_ddjj/EliminarItemDDJJ"

  get "adm_ddjj/EditarGrupoHorarioItemDDJJ"

  get "adm_ddjj/AgregarGrupoHorarioItemDDJJ"

  get "adm_ddjj/EliminarGrupoHorarioItemDDJJ"

  get "adm_ddjj/verDDJJ"

  get "adm_ddjj/verDDJJsAgente"

  get "adm_ddjj/ModificarDDJJ"

  get "adm_ddjj/CargarDDJJ"

  get "adm_ddjj/ListarDDJJs"

  get "adm_ddjj/ListarDDJJsI"

  get "adm_ddjj/verDdjj"

  get "adm_ddjj/ModificarDdjj"

  get "adm_ddjj/CargarDdjj"

  get "adm_ddjj/ListarDdjjs"

  get "adm_ddjj/EliminarDdjj"

  resources :grupo_horario_item_ddjjs

  resources :item_ddjjs

  resources :materia_cargos

  resources :funcions

  resources :ddjjs

  resources :localidads

  resources :provincias

  resources :organizacions

  resources :domicilios

  resources :users

  get "session/login"

  get "session/logout"

  post "relacion_agente_profesion/guardar"
  
 
        
  get "relacion_agente_profesion/agregarProfesionAgente"

  resources :profesion_agentes

  resources :profesions

  resources :agentes

end

app/models/agente.rb
class Agente < ActiveRecord::Base
  #-------------controles relacionales--------
  has_many :profesion_agente
  #-------------validaciones------------------
  validates :dni, :presence => true, :uniqueness => true,  :numericality => true
  
  validates :nombre, :presence => true
  validates :apellido, :presence => true
end

app/models/ddjj.rb
class Ddjj < ActiveRecord::Base
end

app/models/domicilio.rb
class Domicilio < ActiveRecord::Base
end

app/models/funcion.rb
class Funcion < ActiveRecord::Base
end

app/models/item_ddjj.rb
class ItemDdjj < ActiveRecord::Base
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
end

app/models/materia_cargo.rb
class MateriaCargo < ActiveRecord::Base
end

app/models/organizacion.rb
class Organizacion < ActiveRecord::Base
end

app/models/profesion.rb
class Profesion < ActiveRecord::Base
   has_many :profesion_agente
end

app/models/profesion_agente.rb
class ProfesionAgente < ActiveRecord::Base
  #supuestamente comprueba que sea unico el par
  validates :agente_id, :uniqueness => {:scope => :profesion_id}
  #validaciones de existencias
  validates :agente_id, :presence => true
  validates :profesion_id, :presence => true 
  #para establecer la relacion, desde la consola 'rails console' funca
  belongs_to :agente
  belongs_to :profesion
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/localidads_controller.rb
class LocalidadsController < ApplicationController
  # GET /localidads
  # GET /localidads.xml
  def index
    @localidads = Localidad.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @localidads }
    end
  end

  # GET /localidads/1
  # GET /localidads/1.xml
  def show
    @localidad = Localidad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @localidad }
    end
  end

  # GET /localidads/new
  # GET /localidads/new.xml
  def new
    @localidad = Localidad.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @localidad }
    end
  end

  # GET /localidads/1/edit
  def edit
    @localidad = Localidad.find(params[:id])
  end

  # POST /localidads
  # POST /localidads.xml
  def create
    @localidad = Localidad.new(params[:localidad])

    respond_to do |format|
      if @localidad.save
        format.html { redirect_to(@localidad, :notice => 'Localidad was successfully created.') }
        format.xml  { render :xml => @localidad, :status => :created, :location => @localidad }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @localidad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /localidads/1
  # PUT /localidads/1.xml
  def update
    @localidad = Localidad.find(params[:id])

    respond_to do |format|
      if @localidad.update_attributes(params[:localidad])
        format.html { redirect_to(@localidad, :notice => 'Localidad was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @localidad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /localidads/1
  # DELETE /localidads/1.xml
  def destroy
    @localidad = Localidad.find(params[:id])
    @localidad.destroy

    respond_to do |format|
      format.html { redirect_to(localidads_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/adm_ddjj_helper.rb
module AdmDdjjHelper
end

app/helpers/agentes_helper.rb
module AgentesHelper
end

app/helpers/ddj_js_helper.rb
module DdjJsHelper
end

app/helpers/domicilios_helper.rb
module DomiciliosHelper
end

app/helpers/funcions_helper.rb
module FuncionsHelper
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/profesions_helper.rb
module ProfesionsHelper
end

app/helpers/provincias_helper.rb
module ProvinciasHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/localidads/_form.html.erb
<%= form_for(@localidad) do |f| %>
  <% if @localidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@localidad.errors.count, "error") %> prohibited this localidad from being saved:</h2>

      <ul>
      <% @localidad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provincia_id %><br />
    <%= f.text_field :provincia_id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codpos %><br />
    <%= f.text_field :codpos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/localidads/edit.html.erb
<h1>Editing localidad</h1>

<%= render 'form' %>

<%= link_to 'Show', @localidad %> |
<%= link_to 'Back', localidads_path %>

app/views/localidads/index.html.erb
<h1>Listing localidads</h1>

<table>
  <tr>
    <th>Provincia</th>
    <th>Nombre</th>
    <th>Codpos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @localidads.each do |localidad| %>
  <tr>
    <td><%= localidad.provincia_id %></td>
    <td><%= localidad.nombre %></td>
    <td><%= localidad.codpos %></td>
    <td><%= link_to 'Show', localidad %></td>
    <td><%= link_to 'Edit', edit_localidad_path(localidad) %></td>
    <td><%= link_to 'Destroy', localidad, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Localidad', new_localidad_path %>

app/views/localidads/new.html.erb
<h1>New localidad</h1>

<%= render 'form' %>

<%= link_to 'Back', localidads_path %>

app/views/localidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provincia:</b>
  <%= @localidad.provincia_id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @localidad.nombre %>
</p>

<p>
  <b>Codpos:</b>
  <%= @localidad.codpos %>
</p>


<%= link_to 'Edit', edit_localidad_path(@localidad) %> |
<%= link_to 'Back', localidads_path %>